GET https://vanjacloudjs-dev.azurewebsites.net/api/counters/7

###
GET https://vanjacloudjs.azurewebsites.net/api/counters/7

###
GET http://localhost:7071/api/orchestrators/DurableFunctionsOrchestratorJS1

###

POST http://localhost:7071/api/orchestrators/DurableFunctionsOrchestratorJS1

{}

###
GET http://localhost:7071/api/counters/7

###
POST http://localhost:7071/api/counters/7 HTTP/1.1
content-type: application/json
{
     "id": 7
}

###

http://localhost:7071/api/counters/7

###

POST http://localhost:7071/api/counters/7